# This is the name of our CI/CD pipeline
name: Java CI with Maven

# This section defines when the pipeline should run.
on: [push]

# This section defines the actual "jobs" or steps in our assembly line.
jobs:
  build-and-test:
    # This tells GitHub to run our job on the latest version of Ubuntu Linux.
    runs-on: ubuntu-latest

    # These are the sequential steps the job will perform.
    steps:
      # Step 1: Check out the code from our repository.
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the correct Java environment (JDK 21).
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      # Step 3: Build the project and run ALL tests.
      - name: Build and run tests with Maven
        # --- THIS IS THE FIX ---
        # We tell this step to run from inside the 'demo' folder.
        working-directory: ./demo
        run: mvn -B test
